config/routes.rb
Scrumastic::Application.routes.draw do |map|

  resources :websocket_connections

  resources :projects do
    member do 
      get "reports"
      get "collect_test_results"
    end
    resources :attachments
    resources :shouts
    resources :sprint_log_entries
    resources :sprints
    resources :user_stories do
      resources :time_log_entries do
        collection do
          get :start_work
          get :stop_work
        end
      end
      member do
        post :move_to_backlog
        post :move_to_incubator
        post :move_to_sprint
      end
      collection do
        post :sort
      end
      resources :comments
    end
    resources :time_log_entries
  end
  
  resources :user_searches, only: [:create]
  

  root :to => "projects#index"
  

  devise_for :users
end

app/models/comment.rb
# encoding: UTF-8

require 'carrierwave/orm/mongoid'

# Provides simple discussion and file upload mechanism for user stories.
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, :type => String

  belongs_to_related :user
  belongs_to_related :user_story

  references_one :attachment

  # True if user is allowed to edit this comment
  def can_edit?(someone)
    (someone.id == user.id) || (user_story.project.owner.id == someone.id)
  end
end

app/controllers/comments_controller.rb
# encoding: UTF-8

class CommentsController < ProjectScopedController
  before_filter :find_user_story

  before_filter :find_comment, only: [:edit, :show, :update, :destroy]
  respond_to :html, :json

  def index
    Can.see?(current_user, @project) do
      @comments = @user_story.comments
    end
  end

  def new
    Can.see?(current_user, @project) do
      respond_with(@comment = Comment.new)
    end
  end

  def create
    Can.see?(current_user, @project) do
      @comment = Comment.create!(params[:comment].merge(
          user_id: current_user.id, user_story_id: @user_story.id))
      if params[:attachment]
        Attachment.create(comment: @comment, project: @project, file: params[:attachment])
      end
      redirect_to [@project, @user_story]
    end
  end

  def edit
    Can.edit?(current_user, @comment) do
      respond_with(@comment)
    end
  end

  def show
    Can.see?(current_user, @project) do
      respond_with(@comment = @user_story.comments.find(:first, conditions: {id: params[:id]}))
    end
  end

  def update
    Can.edit?(current_user, @comment) do
      @comment.update_attributes(params[:comment].merge(
        user_id: current_user.id, user_story_id: @user_story.id))
      respond_with(@comment)
    end
  end

  def destroy
    Can.edit?(current_user, @comment) do
      @comment.destroy
    end
  end

  protected
  
  def find_comment
    @comment = @user_story.comments.find(params[:id])
  end

  # Finds user story in given project
  def find_user_story
    @user_story = @project.user_stories.find(params[:user_story_id])
  end
end

app/views/comments/_comment.html.haml
.comment{:id => "comment_#{comment.id}_wrapper"}
  - if Can.edit?(current_user, comment)
    .right
      = link_to icon_tag("trash"),                                                                  |
          project_user_story_comment_path(comment.user_story.project, comment.user_story, comment), |
                                         method: "delete", remote: true                             |
  .left
    = image_tag comment.user.small_gravatar_url, title: comment.user.name

  = raw simple_format sanitize(comment.content)
  .clear
  - if !comment.attachment.nil?
    .left
      = icon_tag "document"
    .left
      = link_to File.basename(comment.attachment.file.file.file), [comment.user_story.project, comment.attachment]
  .clear

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>_wrapper").hide("slow");

app/views/comments/index.html.haml
%h3= t("comments.comments")
= render partial: "comment", collection: @comments

%h3= link_to t("comments.new_comment"), "#", :"data-toggle" => "#new_comment_wrapper"

#new_comment_wrapper{:"data-populate-with" => new_project_user_story_comment_path(@project, @user_story)}

app/views/comments/new.html.haml
- form_tag project_user_story_comments_path(@project, @user_story), |
    id: "new_comment_form", multipart: true do                      |
  %p
    %label{:for => "comment_content"}= t("content")
    = text_area_tag "comment[content]"
  %p
    %label{:for => "attachment"}= t("attachment")
    = file_field_tag "attachment"
  %p
    = submit_tag t("submit")