config/routes.rb
Scrumastic::Application.routes.draw do |map|

  resources :websocket_connections

  resources :projects do
    member do 
      get "reports"
      get "collect_test_results"
    end
    resources :attachments
    resources :shouts
    resources :sprint_log_entries
    resources :sprints
    resources :user_stories do
      resources :time_log_entries do
        collection do
          get :start_work
          get :stop_work
        end
      end
      member do
        post :move_to_backlog
        post :move_to_incubator
        post :move_to_sprint
      end
      collection do
        post :sort
      end
      resources :comments
    end
    resources :time_log_entries
  end
  
  resources :user_searches, only: [:create]
  

  root :to => "projects#index"
  

  devise_for :users
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :description, :type => String
  mount_uploader :file, AttachmentUploader

  referenced_in :project
  referenced_in :comment
  validates_presence_of :project_id, :file

  def can_edit?(someone)
    project.involved_people_ids.include?(someone.id.to_s)
  end

  def has_thumb?
    file.thumb.file.path =~ /(png|jpg|jpeg|gif)$/
  end
end

app/controllers/attachments_controller.rb
# encoding: UTF-8

class AttachmentsController < ProjectScopedController
  respond_to :html, :json

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(params[:attachment])
    @attachment.project = @project
    if @attachment.save
      redirect_to [:project, :attachments]
    else
      render action: "new"
    end
  end

  def index
    @attachments = Attachment.paginate(conditions: {project_id: @project.id}, sort: ["updated_at", "desc"],
                                       page: params[:page], per_page: 10)
  end

  def show
    attachment = Attachment.find(params[:id])
    Can.edit?(current_user, attachment) do
      if params[:style] == "thumb"
        safer_send_file attachment.file.thumb.file.file
      else
        safer_send_file attachment.file.file.file
      end
    end
  end

  def destroy
    attachment = Attachment.find(params[:id])
    Can.edit?(current_user, attachment) do
      attachment.destroy
      redirect_to [@project, :attachments]
    end
  end
end

app/views/attachments/_attachment.html.haml
.attachment
  = button_to "", [attachment.project, attachment],             |
            method: "delete",                                   |
            class: "right icon icon-cross",                     |
            "data-confirm" =>  t("attachments.confirm_delete")  |


  = image_tag project_attachment_path(attachment.project, attachment, style: "thumb") if attachment.has_thumb?
  = link_to File.basename(attachment.file.file.file), [attachment.project, attachment]
  = attachment.description
  .meta
    = localize(attachment.created_at, format: :short) + ", "
    = attachment.file.size
    = t("bytes")

  .clear

app/views/attachments/index.html.haml
= render partial: "projects/project_header", locals: {project: @project}
.clear
%p= link_to t("new_attachment"), [:new, @project, :attachment], class: "right button button-with-icon icon-add"
%h1= t("attachments.list")
.clear
= render partial: "attachment", collection: @attachments

= will_paginate @attachments

app/views/attachments/new.html.haml
= render partial: "projects/project_header", locals: {project: @project}

%h1= t("new_attachment")

- form_for [@project, @attachment], html: {multipart: true} do |f|
  = f.error_messages
  %p
    = f.label :file
    = f.file_field :file
  %p
    = f.label :description
    = f.text_field :description
  %p
    = f.submit t("submit")