config/routes.rb
Scrumastic::Application.routes.draw do |map|

  resources :websocket_connections

  resources :projects do
    member do 
      get "reports"
      get "collect_test_results"
    end
    resources :attachments
    resources :shouts
    resources :sprint_log_entries
    resources :sprints
    resources :user_stories do
      resources :time_log_entries do
        collection do
          get :start_work
          get :stop_work
        end
      end
      member do
        post :move_to_backlog
        post :move_to_incubator
        post :move_to_sprint
      end
      collection do
        post :sort
      end
      resources :comments
    end
    resources :time_log_entries
  end
  
  resources :user_searches, only: [:create]
  

  root :to => "projects#index"
  

  devise_for :users
end

app/models/project.rb
# encoding: UTF-8

require 'carrierwave/orm/mongoid'

# It is what it's all about :).
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include ArrayAttributes

  field :name, :type => String
  field :description, :type => String
  field :repository_url, :type => String
  field :application_regexp, :type => String
  field :tests_regexp, :type => String
  field :api_key, :type => String
  array_attributes :team_member_ids, :stakeholder_ids

  belongs_to_related :scrum_master, :class_name => "User"
  belongs_to_related :product_owner, :class_name => "User"
  belongs_to_related :owner, :class_name => "User"
  has_many_related :sprints, :dependent => :destroy
  has_many_related :user_stories, :dependent => :destroy
  has_many_related :shouts, :dependent => :destroy
  references_many :attachments, :dependent => :destroy
  references_many :time_log_entries, :dependent => :destroy
  references_many :remaining_points_metrics, class_name: "Metrics::RemainingPoints", dependent: :destroy
  references_many :velocity_metrics, class_name: "Metrics::Velocity", dependent: :destroy
  references_many :project_size_metrics, class_name: "Metrics::ProjectSize", dependent: :destroy
  references_many :code_complexity_metrics, class_name: "Metrics::CodeComplexity", dependent: :destroy

  mount_uploader :logo, ProjectLogoUploader

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :owner_id
  validate :uniqueness_of_roles

  before_validation :generate_api_key_if_blank

  # People that you can assign user stories to.
  def assignable_people
    assignable_people_ids.collect{|user_id| User.find(user_id)}
  end

  # Ids of people that you can assign user stories to.
  def assignable_people_ids
    ([self.scrum_master_id.to_s] + self.team_member_ids).select {|u_id| !u_id.blank?}
  end

  # True if user is allowed to remove given project
  def can_destroy?(someone)
    can_edit? someone
  end

  # True if user is allowed to edit given project
  def can_edit?(someone)
    owner_id.to_s == someone.id.to_s
  end

  # True if user can edit sprint details for this project
  def can_edit_sprints_for?(someone)
    can_edit?(someone) || 
    (scrum_master_id == someone.id) ||
    (product_owner_id == someone.id)
  end

  # True if user is allowed to edit user stories in project
  def can_edit_user_stories_for?(someone)
    can_edit?(someone) ||
    assignable_people_ids.include?(someone.id.to_s) ||
    (product_owner_id.to_s == someone.id.to_s)
  end

  # True if user is allowed to see project dashboard and user stories
  def can_see?(someone)
    can_edit?(someone) ||
    involved_people_ids.include?(someone.id.to_s)
  end

  # Removes project and associated sprints and user stories
  def destroy
    sprints.each {|sprint| sprint.destroy(true) }
    UserStory.destroy_all(:conditions => {:project_id => id})
    super
  end

  # People that are assigned to this project, including all roles
  def involved_people
    involved_people_ids.collect{|user_id| User.find(user_id)}
  end

  # Ids of people assigned to this project
  def involved_people_ids
    (
      [self.scrum_master_id.to_s, self.product_owner_id.to_s] + self.team_member_ids + self.stakeholder_ids
    ).select {|u_id| !u_id.blank?}
  end

  # People that play a "chicken" role in project - observers
  def stakeholders
    self.stakeholder_ids.collect{|user_id| User.find(user_id)}
  end

  # People being team members
  def team_members
    self.team_member_ids.collect{|user_id| User.find(user_id)}
  end

  def current_time_log_entries
    TimeLogEntry.all(conditions: {current: true, project_id: id})  
  end

  def worked_time(from=created_at, to=Time.zone.now, user_id=nil)
    from = created_at if from.blank?
    to = created_at if to.blank?
    query = {project_id: id, :created_at.gte => from, :created_at.lte => to}
    query.merge!({user_id: user_id}) unless user_id.blank?
    TimeLogEntry.all(conditions: query).collect{|e| e.number_of_seconds}.sum
  end

  def start_date
    sprints.collect {|s| s.start_date.to_date}.min
  end

  def end_date
    sprints.collect {|s| s.end_date.to_date}.max
  end

  def sprint_start_end_dates
    sprints.collect {|s| [s.start_date.to_date, s.end_date.to_date] }.flatten
  end
 
  def repository
    Repository.new(repository_url, id.to_s)
  end 

  private

  # Validates that one user must play only one role in Project.
  # makes project.valid? return false, prevents it from saving
  # and sets project.errors hash with proper message
  def uniqueness_of_roles
    ids = involved_people_ids
    doubled_ids = ids.select {|user_id| ids.index(user_id) != ids.rindex(user_id) }
    if doubled_ids.include?(scrum_master_id.to_s)
      errors[:scrum_master_id] << "must have unique role"
    end
    if doubled_ids.include?(self.product_owner_id.to_s)
      errors[:product_owner_id] << "must have unique role"
    end
    if self.team_member_ids - doubled_ids != self.team_member_ids
      errors[:team_member_ids] << "must have unique role"
    end
    if self.stakeholder_ids - doubled_ids != self.stakeholder_ids
      errors[:stakeholder_ids] << "must have unique role"
    end
  end

  class Repository
    attr_accessor :path

    def initialize(repository_url, project_id)
      @repository_url = repository_url
      @project_id = project_id
      self.path = "/tmp/#{@project_id}"
    end 

    def update
      if @repository_url.blank?
        false
      elsif Dir.exists?("#{path}/.git")
        system "cd #{path} && git pull"
      else 
        system Escape.shell_command(["git", "clone", @repository_url.to_s, path])
      end
    end
  end

  def generate_api_key_if_blank
    if self.api_key.blank?
      self.api_key = (0...50).map{ ('a'..'z').to_a[rand(26)] }.join
    end
  end
end

app/controllers/projects_controller.rb
# encoding: UTF-8

class ProjectsController < AuthenticatedController
  respond_to :html, :json
  
  before_filter :find_user_owned_project, except: [:new, :index, :create, :show, :collect_test_results]

  skip_before_filter :authenticate_user!, only: [:collect_test_results]
  def index
    @projects = [ {product_owner_id: current_user.id},
                  {scrum_master_id: current_user.id},
                  {team_member_ids: current_user.id.to_s},
                  {stakeholder_ids: current_user.id.to_s}
    ].inject([]) { |all, cond| all + Project.where(cond)}
    @owned_projects = Project.where(owner_id: current_user.id)
  end

  def new
    respond_with(@project = Project.new)
  end

  def create
    respond_with(@project = Project.create(params[:project].merge(owner_id: current_user.id)))
  end

  def edit
    Can.edit?(current_user, @project) do
      respond_with(@project)
    end
  end

  def show
    @project = Project.find(params[:id])
    Can.see?(current_user, @project) do
      respond_with(@project)
    end
  end

  def reports
    show
  end

  def update
    Can.edit?(current_user, @project) do
      @project.update_attributes(params[:project].merge(owner_id: current_user.id))
      respond_with(@project)
    end
  end

  def destroy
    Can.destroy?(current_user, @project) do
      @project.destroy
      redirect_to projects_path
    end
  end

  def collect_test_results
    project = Project.find(params[:id])
    raise "Not authorized!" unless project.api_key == params[:api_key]

    if params[:passed]
      passed = Metrics::PassedTests.find_or_initialize_by(date: Time.zone.now.to_date, project_id: project.id)
      passed.value = params[:passed].to_i
      passed.save
    end

    if params[:failed]
      failed = Metrics::FailedTests.find_or_initialize_by(date: Time.zone.now.to_date, project_id: project.id)
      failed.value = params[:failed].to_i
      failed.save
    end
    head :ok 
  end

  protected
  def find_user_owned_project
    @project = current_user.projects.find(params[:id])
  end
end

app/views/projects/_form.html.haml
- form_for @project, html: {id: "project_form", multipart: true} do |f|
  = f.error_messages
  %table
    %tr
      %td.description
        = f.label :name, t("models.project.name")
      %td.one
        %label{:for => "product_owner_droppable" }= t("models.project.roles.product_owner")
      %td.one
        %label{:for => "scrum_master_droppable" }= t("models.project.roles.scrum_master")
      %td.last
        %label{:for => "stakeholders_droppable" }= t("models.project.other_stakeholders")
    %tr
      %td.description
        = f.text_field :name
      %td
        %div{:id => "product_owner_droppable", :class => "person-droppable"}
          = render(partial: "person", object: @project.product_owner) unless @project.product_owner.nil?
        = f.hidden_field :product_owner_id
      %td
        %div{:id=>"scrum_master_droppable", :class => "person-droppable"}
          = render(partial: "person", object: @project.scrum_master) unless @project.scrum_master.nil?
        = f.hidden_field :scrum_master_id
      %td
        %div{:id => "stakeholders_droppable", :class => "person-droppable"}
          = render partial: "person", collection: @project.stakeholders
    %tr
      %td.description
        = f.label :description, t("models.project.description")
      %td{:colspan => 3}
        %label{:for => "team_members_droppable"}= t("models.project.team_members")
    %tr
      %td.description{:rowspan => 3}
        = f.text_area :description, class: "resizable-textarea"
      %td{:colspan => 3}
        %div{:id => "team_members_droppable", :class => "person-droppable"}
          = render partial: "person", collection: @project.team_members
    %tr
      %td{:colspan => 3}
        %label{:for => "available_people"}= t("projects.available_people")
    %tr
      %td{:colspan => 3}
        = render partial: "search_people"
        %div{:id => "available_people", :class => "person-droppable"}
        %div{:id => "available_people_pagination"}

  .vspacer

  %p
    = f.label :logo, t("projects.logo")
    .vspacer
    .left
      = thumb_of @project
    - if @project.logo.present?
      = f.check_box :remove_logo
      = f.label :remove_logo, t("projects.remove_logo"), style: "display: inline"
      %br
    = f.file_field :logo
    .clear
    
  %p
    = f.label :repository_url, t("projects.repository_url")
    = f.text_field :repository_url
  %p
    = f.label :application_regexp, t("projects.application_regexp")
    = f.text_field :application_regexp
  %p
    = f.label :tests_regexp, t("projects.tests_regexp")
    = f.text_field :tests_regexp
  %p
    = f.label :api_key, t("projects.api_key")
    = f.text_field :api_key


  = f.submit t("submit")
  = link_to t("cancel"), :projects

- unless @project.new_record?
  .right
    %table{:class => "adjusting move-three-up"}
      %tr
        %td
          = icon_tag "trash"
        %td
          = button_to t("projects.delete"), @project, "method" => "delete",     |
              confirm: (Rails.env.test? ? false : t("projects.confirm_delete"))    |

.clear

app/views/projects/_person.html.haml
%div{:class => "person-draggable ui-corner-all", :id => "user_#{person.id}_draggable", :userId => "#{person.id}"}
  = person.name
  %br
  = image_tag(person.big_gravatar_url)

app/views/projects/_project_header.haml
= render :partial => "projects/shoutbox"

%input{type: "hidden", id: "current_project_id", value: @project.id}

.left
  = thumb_of project

%h2= link_to project.name, project

%div.description= project.description
%div.description
  = TimeFormatter::format project.worked_time
  = link_to t("details"), project_time_log_entries_path(project)


= link_to t("edit"), edit_project_path(@project) if Can.edit?(current_user, @project)

- if @project.current_time_log_entries.count > 0
  #now_working
    %h2= t("currently_working")
    - @project.current_time_log_entries.each do |entry|
      - if entry.user != nil && entry.user_story
        = link_to image_tag(entry.user.small_gravatar_url, :title => entry.user.name, :alt => entry.user.name), [@project, entry.user_story]

.clear

- content_for :extra_navigation do
  .left
    = link_to t("attachments.list"), [@project, :attachments], class: "button button-with-icon icon-pages"
  - if controller.is_a?(ProjectsController) && action_name == "show"
    #project_buttons
      %input{:type => "checkbox", :id => "sprints_visible", :checked => "checked"}
      %label{:for => "sprints_visible"}= t("projects.sprints")
      %input{:type => "checkbox", :id => "product_backlog_visible", :checked => "checked"}
      %label{:for => "product_backlog_visible"}= t("projects.product_backlog")
      %input{:type => "checkbox", :id => "user_stories_incubator_visible", :checked => "checked"}
      %label{:for => "user_stories_incubator_visible"}= t("projects.user_stories_incubator")

app/views/projects/_radiator.html.haml
- content_for :socky do
  = socky :client_id => current_user.id, :channels => @project.id, :client_secret => current_user.password_salt

#shoutbox
  %div{"data-populate-with" => project_shouts_path(@project) }

app/views/projects/_search_people.html.haml
%label.inline-block{:for => "search_people_text"}
  = t("people.search")
%input{:type => "text", :id => "search_people_text", :size => 60, :class => "nosubmit"}
= loader_icon "people_search"

app/views/projects/_shoutbox.html.haml
- content_for :socky do
  = socky :client_id => current_user.id, :channels => @project.id, :client_secret => current_user.password_salt

#shoutbox
  %div{"data-populate-with" => project_shouts_path(@project) }
    = loader_icon "shoutbox", true

app/views/projects/edit.html.haml
= render partial: "form"

app/views/projects/index.html.haml
.projects
  %h2= t("projects.you_are_involved_in")
  - @projects.each do |project|
    - div_for project do
      = thumb_of(project, 32)
      %h3= link_to project.name, project
      %p
        = project.description
      %p
        = t("projects.your_role_in_project",                                           |
             role: t("models.project.roles.#{current_user.role_in_project(project)}")) |
      .clear
  - if @projects.empty?
    = t("projects.none_involved_in")

.owned_projects
  .right
    %a{:href => new_project_path }
      %span{:class => "ui-icon ui-icon-plus inline-block"}
    %a{:href => new_project_path }
      = t("projects.new_project")

  %h2= t("projects.you_own")
  - @owned_projects.each do |project|
    - div_for project do
      = thumb_of(project, 32)
      .right
        %a.hidden{:href => edit_project_path(project) }
          %span{:class => "ui-icon ui-icon-wrench inline-block"}
        %a.hidden{:href => edit_project_path(project) }
          = t("projects.edit_project")

      %h3= link_to project.name, project
      %p
        = project.description
      .clear
  - if @owned_projects.empty?
    = t("projects.none_owned")

.clear

app/views/projects/new.html.haml
= render partial: "form"

app/views/projects/reports.html.haml
= render partial: "project_header", locals: {project: @project}

%h2= t("projects.reports")
#reports
  = select_tag :from, options_for_select((@project.start_date..@project.end_date).collect {|d| [d.to_s, d.midnight.to_i]}.reverse, @project.start_date.midnight.to_i)
  = select_tag :to, options_for_select((@project.start_date..@project.end_date).collect {|d| [d.to_s, d.end_of_day.to_i]}.reverse)

  %button#plot_timeline Plot


- plot_data = []
- legends = []
- labels = []
- ["project_size", "remaining_points", "velocity", "code_complexity"].each do |metric|
  - data, labels = data_for_chart(@project, @project.send(metric + "_metrics"))
  - unless data.values.all?{|v| v.nil?}
    - plot_data << data.values
    - legends << t("metrics.#{metric}")


= image_tag(Gchart.line(:size => "960x300", :title => t("metrics.plot"), :bg => 'FFFFFF', :legend => legends, :data => plot_data, :axis_with_labels => ["x"], :axis_labels => [labels], :line_colors => "FF0000,00FF00,0000FF,F0F000"))

app/views/projects/show.html.haml
= render partial: "project_header", locals: {project: @project}

#sprints.ui-corner-all
  - if Can.edit_sprints_for?(current_user, @project)
    .right
      %a{"data-toggle" => ".new-sprint-form-wrapper", "href" => "#", "title" => t("sprints.new")}= icon_tag "plus"

  %h2= t("projects.sprints")
  %div{"data-populate-with" => project_sprints_path(@project)}= loader_icon "sprints", true

#product_backlog.ui-corner-all
  %h2= t("projects.product_backlog")
  %div{"data-populate-with" => project_user_stories_path(@project, in_backlog: "true")}= loader_icon "backlog_user_stories", true

#user_stories_incubator.ui-corner-all
  - if Can.edit_user_stories_for?(current_user, @project)
    .right
      %a{"data-toggle" => ".new-user-story-form-wrapper", "href" => "#", "title" => t("user_stories.new")}= icon_tag "plus"

  %h2= t("projects.user_stories_incubator")
  %div{"data-populate-with" => project_user_stories_path(@project, in_backlog: "false")}= loader_icon "incubator_user_stories", true

.clear