config/routes.rb
Scrumastic::Application.routes.draw do |map|

  resources :websocket_connections

  resources :projects do
    member do 
      get "reports"
      get "collect_test_results"
    end
    resources :attachments
    resources :shouts
    resources :sprint_log_entries
    resources :sprints
    resources :user_stories do
      resources :time_log_entries do
        collection do
          get :start_work
          get :stop_work
        end
      end
      member do
        post :move_to_backlog
        post :move_to_incubator
        post :move_to_sprint
      end
      collection do
        post :sort
      end
      resources :comments
    end
    resources :time_log_entries
  end
  
  resources :user_searches, only: [:create]
  

  root :to => "projects#index"
  

  devise_for :users
end

app/models/time_log_entry.rb
class TimeLogEntry
  include Mongoid::Document
  include Mongoid::Timestamps
  referenced_in :project
  referenced_in :user
  referenced_in :user_story
  field :number_of_seconds, type: Integer, default: 0
  field :current, type: Boolean, default: true  

  validates_presence_of :project, :user
  validates_uniqueness_of :current, scope: [:project_id, :user_id], if: Proc.new {|o| o.current == true }
  before_validation :close_current_if_new
  
  def can_edit?(user)
    self.user == user || user.role_in_project(project) == :scrum_master
  end

  def formatted_number_of_seconds
    TimeFormatter::format(number_of_seconds)
  end
  
  def formatted_number_of_seconds=(str)
    begin
      self.number_of_seconds = (Time.parse(str) - Time.parse("00:00:00")).to_i
    rescue ArgumentError
    end
  end

  def nullify
    [:user, :user_story].each do |relation|
      begin
        send(relation)
      rescue Mongoid::Errors::DocumentNotFound
        send "#{relation}=", nil
      end
    end
    save
  end

  def close
    update_attributes current: false, number_of_seconds: Time.zone.now.to_i - created_at.to_i
  end

  def close_current_if_new
    if new_record? && project && user
      TimeLogEntry.all(conditions: {user_id: user.id, project_id: project.id, current: true}).each do |e|
        e.close
      end
    end
  end

  def formatted_created_at=(time)
    begin
      self.created_at = Time.parse(time)
    rescue ArgumentError
      # silently ignore, use default 
    end
  end

  def formatted_created_at
    (created_at ? created_at : Time.zone.now).strftime("%d/%m/%Y %k:%M:%S")
  end


end

app/controllers/time_log_entries_controller.rb
class TimeLogEntriesController < ProjectScopedController
  before_filter :find_user_story, :only => [:start_work, :stop_work]
  before_filter :find_time_log_entry, :only => [:edit, :update]

  def start_work
    TimeLogEntry.create(user: current_user, project: @project, user_story: @user_story)
    redirect_to :back
  end

  def stop_work
   tle = current_user.current_time_log_entry(@project)
   tle.close if tle
   redirect_to :back
  end

  def index
    @from = @project.created_at
    @to = Time.zone.now

    query = {sort: ["created_at", "desc"], page: params[:page], 
             per_page: 20, :conditions => {:project_id => @project.id}}

    if params[:from] && params[:to]
      @from = query[:conditions][:created_at.gte] = Time.parse(params[:from])
      @to = query[:conditions][:created_at.lte] = Time.parse(params[:to]).tomorrow
    end

    unless params[:user_id].blank?
      query[:conditions][:user_id] = BSON::ObjectID.from_string(params[:user_id])
    end

    @time_log_entries = TimeLogEntry.paginate(query)
  end

  def new
    @time_log_entry = TimeLogEntry.new
  end

  def edit; end

  def create
    @time_log_entry = TimeLogEntry.new(params[:time_log_entry])
    @time_log_entry.user = current_user
    @time_log_entry.project = @project
    if @time_log_entry.save
      redirect_to project_time_log_entries_path(@project)
    else
      render action: "new"
    end
  end

  def update
    Can.edit?(current_user, @time_log_entry) do
      @time_log_entry.project = @project
   
      if @time_log_entry.update_attributes(params[:time_log_entry])
        redirect_to project_time_log_entries_path(@project)
      else
        render action: "edit"
      end
    end
  end

  private

  def find_user_story
    @user_story = @project.user_stories.find(params[:user_story_id]) 
  end

  def find_time_log_entry
    @time_log_entry = TimeLogEntry.find(params[:id])
  end
end

app/views/time_log_entries/_form.html.haml
- form_for [@project, @time_log_entry] do |f|
  = f.error_messages
  %p
    = f.label :formatted_created_at, t("start_date")
    = f.text_field :formatted_created_at
  %p
    = f.label :formatted_number_of_seconds, t("worked_time")
    = f.text_field :formatted_number_of_seconds
  %p
    = f.label :user_story_id, t("models.user_story.name")
    = f.collection_select :user_story_id, @project.user_stories.find(:all, sort: ["updated_at", "desc"]), :id, :text
  = f.hidden_field :current, :value => 0
  %p
    = f.submit t("submit")

app/views/time_log_entries/edit.html.haml
= render partial: "projects/project_header", locals: {project: @project} 

%h2
   = image_tag(@time_log_entry.user.medium_gravatar_url, :title => @time_log_entry.user.name)
   = t("time_log_entries.edit")


= render partial: "form"

= link_to t("back"), project_time_log_entries_path(@project)

app/views/time_log_entries/index.haml
= render partial: "projects/project_header", locals: {project: @project}
.right
  = link_to t("time_log_entries.new"), new_project_time_log_entry_path(@project)
.worked-time
  = TimeFormatter::format @project.worked_time(@from, @to, params[:user_id])
- form_tag project_time_log_entries_path(@project), {method: :get, class: "simple-filtering"} do
  = label_tag :from, t("from")
  = text_field_tag :from, params[:from] || @project.created_at.to_date, class: "date-picker", size: 10
  = label_tag :to, t("to")
  = text_field_tag :to, params[:to] || Time.zone.now.to_date, class: "date-picker", size: 10
  = label_tag :user_id, t("user")
  = select_tag :user_id, options_from_collection_for_select(@project.involved_people, "id", "name", selected: params[:user_id]), include_blank: true
 
  = submit_tag t("submit")


- @time_log_entries.each do |entry|
  .time-log-entry
    - if entry.user != nil
      = image_tag entry.user.medium_gravatar_url, :title => entry.user.name

    .entry-date
      = localize entry.created_at, :format => :short
      = link_to t("edit"), edit_project_time_log_entry_path(@project, entry)  if Can.edit?(current_user, entry)

    .entry-duration
      = TimeFormatter::format(entry.number_of_seconds)
    .entry-worked-on
      = t("worked_on")
      = story_text(entry.user_story)

= will_paginate @time_log_entries

app/views/time_log_entries/new.html.haml
= render partial: "projects/project_header", locals: {project: @project} 

%h2= t("time_log_entries.new")
= render partial: "form"

= link_to t("back"), project_time_log_entries_path(@project)